# Generated by Django 5.1.2 on 2024-11-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_assignment_job_assignment_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
